### PR TITLE
allow picking bind ip and default to 127.0.0.1

### PR DESCRIPTION
**Pull request by cvogt**
otherwise I get lots of firewall dialogs asking me if I want to allow external access to this services on OSX

### CODE REVIEW

**Comment by jeep87c** [comment]
Will it be merged soon? I the same issue and it's pretty annoying. See issue #15 I opened moments ago and stackoverflow question:
https://stackoverflow.com/questions/45175931/asking-network-permission-in-intellij-osx-for-each-test-using-scalatest-embedmon

**Comment by ubourdon** [comment]
Hi i try to do that this week end.

**Comment by tg44** [comment]
seems good to me

**Comment by cvogt** [comment]
*bump* :)

**Comment by jeep87c** [comment]
Bump :)

**Comment by jeep87c** [comment]
Bump again

**Comment by lzhuor** [comment]
Bump :P

**Comment by sullis** [comment]
what is the status on this PR?

**Pull request merged**
