### PR TITLE
Migrated to Scala 2.12

### PR DESCRIPTION
**Pull request by Sebruck**
I had to remove `salat` because they will not support Scala 2.12 in the near future.

### CODE REVIEW

**Comment by Sebruck** [comment]
Fixes #12

**Comment by Sebruck** [comment]
Damn, i didn't see that there is already #11 :man_facepalming:

**Comment by ubourdon** [comment]
yep your goal will be done by PR #11 . I close this one if you are ok.

**Comment by ubourdon** [comment]
already DONE with version 0.2.4 of the library.

**Pull request closed without merging**
