### PR TITLE
scala 2.12, mongo 3.x support

### PR DESCRIPTION
**Pull request by tg44**
- updated scala, scalatest, and embeddedMongo versions
- dropped salad and use official mongo scala lib instead
- rewrite tests

### CODE REVIEW

**Comment by ubourdon** [comment]
Hi,

Thx for your pull request.
I have to push some modifs deployed on maven central (version release 0.2.3).
I try to handle your pull request as soon as possible. Next week I think.

**Comment by tg44** [comment]
I fixed the CI too :) I have no idea how many user this lib have, but I needed a scala 2.12 version so I updeted all the versions.
I can use this from jitpack until you haven't released it officially.

**Comment by tg44** [comment]
Any progress?

**Comment by ubourdon** [comment]
Sorry. I do my job this week. I swear. :D

**Comment by ubourdon** [comment]
For info, i will handle your PR this saturday. Sorry for the wait.

**Comment by ubourdon** [comment]
@tg44 If you are ok i will deploy this PR to 2.4-SNAPSHOT version first. And if it is ok, one week after (that give me time to test it is ok on my projects) i could deploy in a RELEASE version 2.4.

**Comment by ubourdon** [comment]
I merge your PR locally on my conputer. I deploy on maven central with the version 0.2.4-SNAPSHOT.

Unit tests pass but I have exception when run tests :  
```
NFOS: Exception in monitor thread while connecting to server localhost:33333
com.mongodb.MongoSocketOpenException: Exception opening socket
	at com.mongodb.connection.AsynchronousSocketChannelStream$OpenCompletionHandler.failed(AsynchronousSocketChannelStream.java:253)
	at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:128)
	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishConnect(UnixAsynchronousSocketChannelImpl.java:278)
	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:198)
	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(UnixAsynchronousSocketChannelImpl.java:213)
	at sun.nio.ch.KQueuePort$EventHandlerTask.run(KQueuePort.java:301)
	at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at sun.misc.InnocuousThread.run(InnocuousThread.java:74)
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishConnect(UnixAsynchronousSocketChannelImpl.java:252)
	... 8 more
```

**Comment by tg44** [comment]
I'm not on my dev env right now, but this ex is not just a random log from that line/exception?
https://github.com/tg44/scalatest-embedmongo/blob/updated-versions/src/test/scala/com/github/simplyscala/MongoEmbedDatabaseImmutableTest.scala#L18
If it is, I think this is just some sideeffect and it's the "proper" working ;)
Or my test is trying to catch an exception at the wrong place, and the connect (L14) throw one too.
I will check this tomorrow morning.

**Comment by ubourdon** [comment]
If you reference 0.2.4-SNAPSHOT in your sbt file you succeed to download your version lib ?

**Comment by tg44** [comment]
0.2.4-Snapshot works as expected.
The error on the log is from the com.mongo scala connector, it's log an exception before it's drop it.

**Comment by ubourdon** [comment]
Hi,
I will use your PR to upgrade sbt version to 0.13.13 and use [coursier](https://github.com/coursier/coursier) to fecth de dependencies.
I will try to also use [sbt sonatype plugin](https://github.com/xerial/sbt-sonatype) to simplify RELEASE process.

**Comment by ubourdon** [comment]
@tg44 i push your PR on master with 0.2.4-SNAPSHOT version.
I will try the release process (for 0.2.4 version) soon.

**Comment by ubourdon** [comment]
@tg44 Do you want I add you as developer in `pom extra` part of the lib ?

**Comment by tg44** [comment]
you can add me :)

**Comment by ubourdon** [comment]
RELEASE of version 0.2.4 with your PR is DONE. I wait sonatype replicate the release for testing all is ok.

**Comment by ubourdon** [comment]
@tg44 It is ok on your side for the 0.2.4 version ?

**Comment by tg44** [comment]
working as expected

**Comment by ubourdon** [comment]
perfect. I close the PR. Thx for your job.

**Pull request closed without merging**
